### PR TITLE
Fabric Gametest

### PR DESCRIPTION
**Pull request by kirderf1**
Currently facing a problem where the game test crashes while loading mixins with a NullPointerException, indirectly caused by
`[main/WARN] (mixin) Error loading class: net/minecraft/world/level/storage/LevelStorage$Session (java.lang.ClassNotFoundException: net/minecraft/world/level/storage/LevelStorage$Session)`
when loading the mixin at https://github.com/FabricMC/fabric/blob/1.17/fabric-gametest-api-v1/src/main/java/net/fabricmc/fabric/mixin/gametest/server/MainMixin.java#L58
I understand it to be some mappings + mixin loader issue, but not enough to tell where to go from here.

### CODE REVIEW

**Comment by canitzp** [comment]
Maybe this is due to us using the official mappings instead of the yarn ones?

**Comment by kirderf1** [comment]
Right now I am under the belief that it's an issue in architectury loom, where it failed to translate to the right mappings.
We could either wait and see if something happens with it in architectury loom, or try to circumvent the issue by switching to yarn mappings (which I'm not too keen to switch to just yet)

**Comment by canitzp** [comment]
I really don't want to switch mappings at all. Official is in my eyes the future

**Comment by kirderf1** [comment]
Gonna keep watch on https://github.com/FabricMC/fabric/issues/1722 to see if that issue progresses in any way.

**Comment by kirderf1** [comment]
architectury/architectury-loom#51 same issue reported on the architectury loom repository.

**Comment by kirderf1** [comment]
The previous issue has now been solved in fabric api, and any remaining issues has now been solved. We have a very basic test, but it's enough to indirectly check for fabric server startup issues. I'm planning on doing additional tests in a separate PR sometime after this one.

**Pull request merged**
