### PR TITLE
Fix the bag that drawing in all creative tabs

### PR DESCRIPTION
**Pull request by ghost**
Hi Lorddusk,

In minecraft 1.12.2,
The bag item draw in all creative tab and i pull this request to fix it (this file is the last update)
bag

And fix the issue: [#381](https://github.com/lorddusk/HQM/issues/381)

### CODE REVIEW

**Comment by canitzp** [comment]
I know that this fixes the bug, but even if I gonna merge this there isn't coming a 1.12.2 update anytine soon, since we are working on the rewrite

**Comment by ghost** [comment]
Ok, it's not a problem but you merge this after the rewrite or you fix it manually ?
if manually, you can close this request :+1:

**Comment by canitzp** [comment]
It is fixed in the rewrite

**Comment by canitzp** [comment]
@TokyoSU I see that you have a good portion of knowledge bout Mc Modding and HQM and I want to ask if you want to help develop the rewrite version? You can join the HQM Discord https://discord.gg/7QRxJMn

**Comment by ghost** [comment]
i just have the basic,
i'm not a pro and i dont speak english, i dont know about Networking,
i can help you just for basic for block / item & metadata / basic gui / color like name & tooltip / and other basic thing, but your hqm is the most complicated system i view (i just view the old).
but thanks to invite me :)

**Pull request closed without merging**
