### PR TITLE
implements ingame gui config

### PR DESCRIPTION
**Pull request by way2muchnoise**

### CODE REVIEW

**Comment by lorddusk** [comment]
does this keep the password protected hqm files in order?

**Comment by way2muchnoise** [comment]
Password protected files? Which would those be?

**Comment by hilburn** [comment]
@lorddusk - this is just for the .cfg files, so they aren't password protected

**Comment by lorddusk** [comment]
I know. but changing the edit mode will skip the protection build in to
stop people from editing quests if the password isn't present.

**Comment by hilburn** [comment]
Looks like it only changes hqmconfig.cfg rather than editmode.cfg

**Comment by way2muchnoise** [comment]
@hilburn yup and we on IRC just said that to @lorddusk

**Comment by lorddusk** [comment]
yeah, just got that same info over irc. I overlooked it in my hurry.

**Pull request merged**
