### PR TITLE
Change the drawRewardMouseOver call from `renderTooltipL` to `renderComponentTooltip`

### PR DESCRIPTION
**Pull request by Mrbysco**
Fixes the stack tooltip not wrapping issue reported in #675

### CODE REVIEW

**Review by kirderf1 — COMMENTED** [review]
While there might be something I'm not seeing that might be apparent when doing some testing, both `renderTooltipL()` and `renderComponentTooltip()` appear to be doing the same thing. They map the list to one of `FormattedCharSequence`s. The mapping is done in different ways, but essentially end up with each element passed through `Language.getInstance().getVisualOrder()`. Both functions then call the same base function for rendering tooltips. There are some slight differences in caching, but I'm not seeing any difference that might be related to the issue.

Depending on where exactly the problem is, it might be relevant to fix this same issue in other places as well.

Indents were changed to tabs on two rows which does not match the existing style. I don't think it's a big deal, but something to be mindful of if you make further changes.

**Comment by Mrbysco** [comment]
This issue is easily reproduce-able by giving yourself an item with an insane decently long lore like with this command https://pastebin.com/dMEKsaCQ and using that item as a reward for a quest.

I have no idea why exactly renderTooltipL doesn't wrap properly, I was mostly looking for a solution for Darkosto's issue.

**Comment by kirderf1** [comment]
Okay, did some testing in debug mode and figured things out.
The source code I was looking at was specifically the unpatched, platform-independent minecraft code. However, forge patches in a hook that processes the text components through `ForgeHooksClient.gatherTooltipComponents()`, which appear ton handle line wrapping. This hook is found in `renderComponentTooltip()`, but not `renderTooltip()` which is called from `renderTooltipL()`.

Fabric does not have a corresponding patch, and on its own lacks text wrapping at all, including in the regular inventory.

With that in mind, we should look for other tooltip rendering in HQM which we may rather want to use `renderComponentTooltip()` for. The menu for picking items being one such place.

This would then specifically affect the version of forge. To consider the fabric version as well, we could look for a fabric mod which adds these line wraps, and then identify if we need to do something special for line wraps from that mod to apply to our tooltips.

**Comment by Mrbysco** [comment]
Based on your findings, what would be the best course of action for me to take?

**Comment by kirderf1** [comment]
Sorry for the slow response. There should be two things that needs answering:
- Should something be done about this for the fabric version version as well, or should this PR continue to focus on fixing this specifically for forge?
- Are other tooltips in the mod affected by this issue? Are there any of those that are relevant to fix as well?

I'm fine merging this regardless of the answer to the first one. However I'd like for you to look into the second one if you think you've got the time for it.

**Comment by Darkosto** [comment]
The tooltips specifically fixed in this PR are the only tooltips I have come across with this issue. There shouldn't be a need to fix any other tooltips.

**Pull request merged**
