### PR TITLE
Backport 5.0.0beta3 to 1.7.10

### PR DESCRIPTION
**Pull request by clienthax**
So. this happened ;)

### CODE REVIEW

**Comment by Dream-Master** [comment]
So that mean now HQM save in Json Format for 1.7.10 ?

**Comment by way2muchnoise** [comment]
If this gets merged, yes

**Comment by Dream-Master** [comment]
very nice work then. Maybe have to change all Quests back from Better Questing mod.
I only move to this mod because May Savegame was all week corrupt but if this is gone i am willing to come back :)

**Comment by Dream-Master** [comment]
@way2muchnoise 
And get this merged or not ?

**Comment by lorddusk** [comment]
Not until I have completely reviewed the changes. Also asking about it, WON'T HELP.

**Comment by way2muchnoise** [comment]
this is quite a big one @Dream-Master so we'll just wait for @lorddusk to have gone over them

**Comment by Dream-Master** [comment]
Sure I just ask not rush anyone.

**Comment by MJRLegends** [comment]
Yay nice to see this might be merged

**Comment by AshIndigo** [comment]
Hey just to let you know in Tuple#getSecond you make it return getSecond which loops and crashes the game. I fixed it by changing to return second.

**Comment by BlayzerQ** [comment]
Who can compile this?

**Comment by AshIndigo** [comment]
Im able to using graldew build but not in eclipse

**Comment by BlayzerQ** [comment]
Please, compile this to jar file. :c

**Comment by clienthax** [comment]
@AshIndigo Nice catch

**Comment by BlayzerQ** [comment]
Crash with click on "Edit text" in Multiplayer:
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
    at hardcorequesting.client.interfaces.edit.GuiEditMenuTextEditor.<init>(GuiEditMenuTextEditor.java:124)
    at hardcorequesting.quests.QuestSet.mouseClickedOverview(QuestSet.java:687)
    at hardcorequesting.client.interfaces.GuiQuestBook.func_73864_a(GuiQuestBook.java:765)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
    at hardcorequesting.client.interfaces.GuiQuestBook.func_146274_d(GuiQuestBook.java:663)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at launcher.client.ClientLauncher.launch(ClientLauncher.java:285)
    at launcher.client.ClientLauncher.main(ClientLauncher.java:186)

**Comment by lorddusk** [comment]
Well don't edit stuff in multiplayer.

**Comment by BlayzerQ** [comment]
On Singleplayer the same crash.
java.lang.NullPointerException: Updating screen events
    at hardcorequesting.client.interfaces.edit.GuiEditMenuTextEditor.<init>(GuiEditMenuTextEditor.java:124)
    at hardcorequesting.quests.QuestSet.mouseClickedOverview(QuestSet.java:687)
    at hardcorequesting.client.interfaces.GuiQuestBook.func_73864_a(GuiQuestBook.java:765)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
    at hardcorequesting.client.interfaces.GuiQuestBook.func_146274_d(GuiQuestBook.java:663)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at launcher.client.ClientLauncher.launch(ClientLauncher.java:285)
    at launcher.client.ClientLauncher.main(ClientLauncher.java:186)

**Comment by BlayzerQ** [comment]
And quest from server dont send to client. Server sync enabled.

**Comment by AshIndigo** [comment]
Looks like one of the params is null can you add some steps on how to replicate it?

**Comment by BlayzerQ** [comment]
Hmmm, i del all configs, repeat this.. and dont crash. (Click "Edit text" and click on text.)

**Comment by BlayzerQ** [comment]
How convert old quest files (4.4.4 qhm) to new format (5.0.0 hqm)?

**Comment by lorddusk** [comment]
Ok, enough is enough. I am closing this for comments... This is a PR, not an issue commenting place...

**Comment by canitzp** [comment]
Only that everyone know it, I closed it since if we merge it, release a version and in the version are bugs or crashes, like we experience a lot with the json format versions, we can't update it so easily.

**Comment by lorddusk** [comment]
This, and because we as a community need to phase out the older versions and move on to the newer. And updating/maintaining for 17 different versions (yes I'm exaggerating) costs a lot of time.

**Pull request closed without merging**
